### ISSUE TITLE
AREPL uses python which causes error on mac (where python refers to python 2)

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL#15]
In mac python refers to python 2 by default.

see https://stackoverflow.com/questions/5846167/how-to-change-default-python-version
same issue with ubuntu: https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3

> Uncaught Error: KeyError: '\_\_loader\_\_'
    at PythonShell.parseError (/Users/anon/Documents/AREPL/node_modules/python-shell/index.js:183:17)
    at terminateIfNeeded (/Users/anon/Documents/AREPL/node_modules/python-shell/index.js:98:28)
    at ChildProcess.<anonymous> (/Users/anon/Documents/AREPL/node_modules/python-shell/index.js:88:9)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
    ----- Python Traceback -----
    File "/Users/anon/Documents/AREPL/src/python/pythonEvaluator.py", line 14, in <module>
      startingLocals[var] = locals()[var]

**Comment by Almenon** [comment]
fixed by changing command to python3 if not windows OS
