### ISSUE TITLE
((k,v) for (k,v) in dictVar) causes error

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL#37]
does not work:
```python
d = {'a':5}
x = ((k,v) for (k,v) in d)
```

does work:
```
d = {'a':5}
x = ((k,v) for (k,v) in d.items())
x = [(k,v) for k,v in d.items()]
x = {k:v for k,v in d.items()}
x = ((k) for k in d)
```

> ⚠ There has been a error when trying to display your variables. Sorry :( 

> Traceback (most recent call last):
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\pythonEvaluator.py", line 77, in exec_input
    returnInfo['userVariables'] = jsonpickle.encode(userVariables, max_depth=100) # any depth above 245 resuls in error and anything above 100 takes too long to process
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\__init__.py", line 135, in encode
    numeric_keys=numeric_keys)
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\pickler.py", line 44, in encode
    return backend.encode(context.flatten(value, reset=reset))
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\pickler.py", line 157, in flatten
    return self._flatten(obj)
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\pickler.py", line 161, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\pickler.py", line 177, in _flatten_obj
    return flatten_func(obj)
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\pickler.py", line 429, in _flatten_dict_obj
    flatten(k, v, data)
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\pickler.py", line 498, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\pickler.py", line 161, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\pickler.py", line 177, in _flatten_obj
    return flatten_func(obj)
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\pickler.py", line 235, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "C:\Users\anon\Downloads\arepl-win32-x64\arepl-win32-x64\resources\app\src\python\jsonpickle\pickler.py", line 367, in _flatten_obj_instance
    data[tags.ITERATOR] = list(map(self._flatten, islice(obj, self._max_iter)))
  File "<string>", line 2, in <genexpr>
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Almenon** [comment]
ported this over to AREPL-backend
