### ISSUE TITLE
make sure app works on linux

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL#54]
i don't have any linux OS to test with

**Comment by Duroktar** [comment]
I gave it a spin this morning on Arch Linux. A few things bugs I hit right away:

1. The executable file `arepl` has to be set to an executable by running chmod on the file before attempting to run it.

```
$ chmod +x arepl
$ ./arepl
```

2. It would appear the packager is not including all the files it should, specifically `app-update.yml`. And on startup I received this error because of that:
```
Checking for update
Checking for update...
Error: Error: ENOENT: no such file or directory, open '/home/duroktar/arepl-linux-x64/resources/app-update.yml'
    at /home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/src/AppUpdater.ts:334:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/src/AppUpdater.ts:98:43)
    at Lazy.get value [as value] (/home/duroktar/arepl-linux-x64/resources/app/node_modules/lazy-val/src/main.ts:18:23)
    at /home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/src/AppUpdater.ts:245:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at App.createWindow (/home/duroktar/arepl-linux-x64/resources/app/src/electron/main.js:88:15)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
{ Error: ENOENT: no such file or directory, open '/home/duroktar/arepl-linux-x64/resources/app-update.yml'
    at /home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/src/AppUpdater.ts:334:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/src/AppUpdater.ts:98:43)
    at Lazy.get value [as value] (/home/duroktar/arepl-linux-x64/resources/app/node_modules/lazy-val/src/main.ts:18:23)
    at /home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/src/AppUpdater.ts:245:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/home/duroktar/arepl-linux-x64/resources/app/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at App.createWindow (/home/duroktar/arepl-linux-x64/resources/app/src/electron/main.js:88:15)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
  cause:
   { Error: ENOENT: no such file or directory, open '/home/duroktar/arepl-linux-x64/resources/app-update.yml'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/home/duroktar/arepl-linux-x64/resources/app-update.yml' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/duroktar/arepl-linux-x64/resources/app-update.yml' }
```

3 - At this point I'm not sure if the app is crashed is the background or not, but the `Open File` dialog box will not appear and attempting to run the interpreter (ie: F5) doesn't have any effect. I also tried `ctrl-enter` from the new-features and it has no effect either.

Great project though, very good idea! Let me know if I can try anything else for you. Cheers :beers:

**Comment by Almenon** [comment]
Well that figures.  Does my vscode extension work at least?

**Comment by Duroktar** [comment]
Checking it now ..

**Comment by Duroktar** [comment]
Getting the error:
```
command 'extension.evalPythonInRealTime' not found
```
I can't see the console output though.

This was also on Arch Linux.

**Comment by Almenon** [comment]
Ugggg.  Looks like i will have to get a linux VM to try to debug the error.

**Comment by Duroktar** [comment]
Is there a way for me to see the error output of the extension? I can provide some assistance possibly. I checked the debug terminal and looked for an extension console but no luck.

**Comment by Almenon** [comment]
I'm presuming you're talking about the electron app - no.  If there is an error once the app has loaded it gets logged to the console but if the app fails in the electron code (https://github.com/Almenon/AREPL/tree/master/src/electron) there is nothing to see short of cloning the repo & debugging it.  

I should add logging in there but currently I am focusing on the vscode extension, which is actually getting downloads.  Apparently no-one wants to download a 50mb electron app :/

**Comment by Duroktar** [comment]
Plus VS-Code is just really popular so that's probably a reason as well. I'll try and find some time this week to get a clone up and running and see what I can find. Can't say when it will be though; I coded most of yesterday so I should probably spend some quality time with the family today :) 

Cheers

**Comment by Almenon** [comment]
Yeah you've been coding like a machine lol.
You sure you're not actually an AI escaped from Yudkowsky's labratory?

**Comment by Duroktar** [comment]
Haha, maybe ;) I know my computer sleeps more than I do though, lol

**Comment by Almenon** [comment]
I have a theory about why arepl-vscode fails on linux - Maybe the permissions are not set correctly.  I was just reading https://code.visualstudio.com/docs/extensions/publish-extension#_common-questions:

> Q: Why does vsce not preserve file attributes?

A: Please note that when building and publishing your extension from Windows, all the files included in the extension package will lack POSIX file attributes, namely the executable bit. Some node_modules dependencies rely on those attributes to properly function. Publishing from Linux and macOS works as expected.

So maybe all I need to do is just build on a linux VM.  I'll use Ubuntu as that is the most popular distro.  Alternatively, maybe I can use WSL (bash on ubuntu on windows)

https://github.com/Microsoft/vscode/issues/13138

**Comment by Almenon** [comment]
@Duroktar I just fixed this for my vscode extension - it turned out to be a case issue.  see https://github.com/Almenon/AREPL-vscode/issues/47
